### PR TITLE
Fix Drafts

### LINKED ISSUE #292: Bug draft signature
When a draft is clicked to start editing, sometimes the signature is added to the body but shouldn't.

### PR DESCRIPTION
**Pull request by Lnamw**
Fixes #292

### CODE REVIEW

File: MailCore/Models/Draft.swift [hunk 1]
```diff
@@ -290,12 +290,14 @@ public struct UnmanagedDraft: Equatable, Encodable, AbstractDraft {
...
         from = [Recipient(email: signature.sender, name: signature.fullName)]
         replyTo = [Recipient(email: signature.replyTo, name: "")]
-        let html = "<div><br></div><div><br></div><div class=\"editorUserSignature\">\(signature.content)</div>"
-        switch signature.position {
-        case .top:
-            body.insert(contentsOf: html, at: body.startIndex)
-        case .bottom:
-            body.append(contentsOf: html)
+        if !body.contains("editorUserSignature") {
+            let html = "<div><br></div><div><br></div><div class=\"editorUserSignature\">\(signature.content)</div>"
```
Comment (valentinperignon) [inline MailCore/Models/Draft.swift:294]:
```suggestion
            let html = "<br><br><div class=\"editorUserSignature\">\(signature.content)</div>"
```
You can do the same on line 258

**Review by valentinperignon — DISMISSED** [review]

**Review by PhilippeWeidmann — APPROVED** [review]

**Review by valentinperignon — APPROVED** [review]
